### ISSUE TITLE
Images appearing upside down...

### ISSUE THREAD

**Issue by robintw** [glue-viz/glue-geospatial#7]
Images imported using this new DataFactory display 'upside down' (I _really_ should have noticed this on the phone the other day, but didn't).

There are some issues with GDAL and matplotlib, basically one counts the opposite way to the other (Y values increase up the axis in one, and down the axis in the other). However, having loaded data in using GDAL a lot in Python before, I've never actually run into the problem.

Before I look into it specifically with rasterio and try and work out what is going on, is there any glue-specific code that might be affecting this (eg. manually setting the origin when running `imshow`)?

**Comment by astrofrog** [comment]
@robintw - good catch! Glue does appear to default to `origin='lower'`. The easy solution at this stage is to always flip the data in the data factory before adding components (this is a cheap operation since it's done as a Numpy view). The more involved solution would be allowing the image viewer to have an option to flip the image vertically. It would be difficult to guess what the correct setting is, so the easier solution might be better - in that we just need to adopt a convention and stick to it?

**Comment by robintw** [comment]
Yup, flipping the data in the DataFactory sounds good.

(And I'm glad to hear that there is a `origin='lower'` argument by default in Glue, I wondered why I hadn't run into this problem before!)

**Comment by astrofrog** [comment]
@robintw - by the way, I've given you push access to this repository, so feel free to add the fix and close this issue!

**Comment by robintw** [comment]
Fixed in a2ec369
